os: linux
dist: xenial

language: node_js

node_js:
  - 17

install:
    - nvm use 17
    - npm install -g gulp-cli
    - npm install
    - gulp --version
    
script:
    - gulp build --profile kbharkiv-staging

deploy:
    - provider: s3
      access_key_id: ${AWS_ACCESS_KEY}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      bucket: static.kbharkiv.dk
      cache_control: 'no-cache'
      local_dir: dist
      upload_dir: kildeviser-development
      acl: public_read
      region: eu-west-1
      on:
        repo: CopenhagenCityArchives/kildeviseren
        branch: development
      edge: true
      cleanup: false

    - provider: s3
      access_key_id: ${AWS_ACCESS_KEY}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      bucket: static.kbharkiv.dk
      cache_control: 'no-cache'
      local_dir: dist
      upload_dir: kildeviser
      acl: public_read
      region: eu-west-1
      on:
        repo: CopenhagenCityArchives/kildeviseren
        branch: master
      edge: true
      cleanup: false
    
    - provider: s3
      access_key_id: ${AWS_ACCESS_KEY}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      bucket: static.kbharkiv.dk
      cache_control: 'no-cache'
      local_dir: dist
      upload_dir: kildeviser-staging
      acl: public_read
      region: eu-west-1
      on:
        repo: CopenhagenCityArchives/kildeviseren
        branch: staging
      edge: true
      cleanup: false