os: linux
dist: xenial

language: node_js

install:
    - ls -l
    - npm install -g gulp-cli
    - npm install
    - gulp --version
    - npm ls gulp-util
    
script:
    - ls -l
    - gulp build 
    - ls -l

deploy:
    - provider: s3
      access_key_id: ${AWS_ACCESS_KEY}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      bucket: static.kbharkiv.dk
      cache_control: 'no-cache'
      local_dir: dist
      upload_dir: kildeviser
      acl: public_read
      region: eu-west-1
      on:
        repo: CopenhagenCityArchives/kildeviseren
        branch: feature-travis
      edge: true
      cleanup: false
