name: Build and deploy

on:
  push:
    branches: [ "staging", "production" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 17
      uses: actions/setup-node@v4
      with:
        node-version: 17

    - name: Install node and gulp cli
      run: |
        npm install -g gulp-cli
        npm install
        gulp --version

    - name: "Run gulp config: ${{ vars.BUILD_CONFIG }}"
      run: |
        gulp build -p ${{ vars.BUILD_CONFIG }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
       role-to-assume: arn:aws:iam::282251075226:role/gh-deploy-s3-cloudfront
       aws-region: eu-west-1

    - name: "Upload to S3: ${{ vars.AWS_BUCKET }} / ${{ vars.DEPLOY_DIR }}"
      env:
        LOCAL_DIR: dist
        AWS_BUCKET: ${{ vars.AWS_BUCKET }}
        DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
      run: |
        aws s3 sync "$LOCAL_DIR" "s3://${AWS_BUCKET}/${DEPLOY_DIR}"

    - name: Request Invalidation to AWS Cloudfront
      env:
        CLOUDFRONT_DISTRIBUTION: ${{ vars.CLOUDFRONT_DISTRIBUTION }}
        PATHS: /*
      run: |
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "$PATHS"
