name: Build and deploy

on:
  push:
    branches: [ "staging", "master" ]
  pull_request:
    branches: [ "staging", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
     name: ${{ github.REF_NAME }}

    strategy:
      matrix:
        node-version: [17]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node and gulp cli
      run: |
        npm install -g gulp-cli
        npm install
        gulp --version

    - name: Run gulp
      run: |
        gulp build -p ${{ vars.BUILD_CONFIG }}

    - name: Upload S3
      uses: shallwefootball/upload-s3-action@v1.3.3
      with:
       aws_key_id: ${{ secrets.AWS_KEY_ID }}
       aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
       aws_bucket: ${{ vars.AWS_BUCKET }}
       source_dir: dist
       destination_dir: ${{ vars.DEPLOY_DIR }}